//
// Purpose: run ml/model.onnx in Node (onnxruntime-node) and check that it gives the same answers
// as sklearn. The test rows + sklearn probabilities are in ml/parity.local.json (generated by
// train.py, not in git). The consumer follows this same path: feature order from model.json,
// float32 tensor.
//
// Run (Git Bash, from the api/ folder):   npm run parity

import { readFile } from "node:fs/promises";
import path from "node:path";
import * as ort from "onnxruntime-node";

const ML_DIR = process.env.ML_DIR || path.join(import.meta.dirname, "..", "..", "ml");
const TOLERANCE = 1e-5; // float32 sum error + parity file's 6-decimal rounding are far smaller

function fail(msg) {
  console.error(`FAIL: ${msg}`);
  process.exit(1);
}

async function readJson(name) {
  try {
    return JSON.parse(await readFile(path.join(ML_DIR, name), "utf8"));
  } catch (err) {
    fail(`could not read ${name} (${err.code || err.message}) - first, from ml/: uv run python train.py`);
  }
}

const meta = await readJson("model.json");
const parity = await readJson("parity.local.json");

// Wrong order = the model reads the wrong columns, and no error is raised. So check this first.
if (JSON.stringify(meta.features) !== JSON.stringify(parity.features)) {
  fail(`feature order differs: model.json ${meta.features} vs parity ${parity.features}`);
}
const n = parity.rows.length;
const k = meta.features.length;
if (n === 0) fail("parity has 0 rows - an empty check does not count as PASS");
if (parity.proba_attack.length !== n) fail("rows and proba_attack have different counts");
if (parity.rows.some((r) => r.length !== k)) fail(`every row needs ${k} numbers`);

// [row0's 9, row1's 9, ...] as one long float32 array -> shape [n, k] says where to split it
const data = new Float32Array(n * k);
parity.rows.forEach((row, i) => data.set(row, i * k));

const session = await ort.InferenceSession.create(path.join(ML_DIR, "model.onnx"));
console.log(`model  : inputs [${session.inputNames}]  outputs [${session.outputNames}]`);
console.log(`rows   : ${n} x ${k} features (${meta.features.join(", ")})`);

const t0 = performance.now();
const out = await session.run({ [meta.input]: new ort.Tensor("float32", data, [n, k]) });
const ms = performance.now() - t0;

const proba = out.probabilities.data; // Float32Array, 2 numbers per row: [benign, attack]
const label = out.label.data; // BigInt64Array (int64) -> compare via Number()

let maxDiff = 0;
let mismatch = 0;
let ties = 0;
for (let i = 0; i < n; i++) {
  const expected = parity.proba_attack[i];
  maxDiff = Math.max(maxDiff, Math.abs(proba[i * 2 + 1] - expected));
  if (expected === 0.5) ties++; // on a tie sklearn picks the first class (0)
  const expectedLabel = expected > 0.5 ? 1 : 0;
  if (Number(label[i]) !== expectedLabel) mismatch++;
}

console.log(`parity : max |proba diff| ${maxDiff.toExponential(2)}   label mismatch ${mismatch}   50-50 ties ${ties}`);
console.log(`time   : ${ms.toFixed(1)} ms for ${n} rows (${((ms / n) * 1000).toFixed(1)} us/row)`);

if (maxDiff < TOLERANCE && mismatch <= ties) {
  console.log("\nSELF-CHECK PASS: Node ONNX output matches sklearn on every row");
} else {
  fail("Node and sklearn give different answers");
}
